object DependencyVersions {
    const val kotlinVersion = "1.7.10"
    const val androidGradleVersion = "7.2.2"
    const val lifecycleVersion = "2.5.1"
    const val fragmentKtx = "1.5.1"
    const val navigationVersion = "2.5.1"
    const val coreKtxVersion = "1.8.0"
    const val appcompatVersion = "1.4.2"
    const val materialVersion = "1.6.1"
    const val constraintLayoutVersion = "2.1.4"
    const val roomVersion = "2.4.3"
    const val coroutinesAndroidVersion = "1.6.0"
    const val coroutinesCoreVersion = "1.6.1"
    const val hiltAndroidVersion = "2.43.2"
    const val glideVersion = "4.12.0"
    const val retrofitVersion = "2.9.0"
    const val okhttpVersion = "5.0.0-alpha.7"
    const val moshiVersion = "1.13.0"
    const val kotlinxDatetimeVersion = "0.4.0"
    const val timberVersion = "5.0.1"

    // Test dependency versions
    const val junitVersion = "4.13.2"
    const val truthVersion = "1.1.3"
    const val coroutinesTestVersion = "1.6.1"
    const val turbineVersion = "0.8.0"
    const val mockkVersion = "1.11.0"
}
